/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vistas;

import Modelo.Aswos;
import Modelo.Fuente;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import javax.imageio.ImageIO;

/**
 *
 * @author Jhh
 */
public class panelEscenario extends javax.swing.JPanel {
    int width, height;
 
    int rows;

    int cols;

    
  
    BufferedImage image;
    /**
     * Creates new form panelEscenario
     */
    public panelEscenario(int w, int h, int r, int c) {
        initComponents();
        setSize(width = w, height = h);
        rows = r;
        cols = c;
        cargarImagen();
        
        width = getSize().width;
        height = getSize().height;
    }
    public void cargarImagen(){
     try {
         image = ImageIO.read(getClass().getClassLoader().getResource("altavoces-rectangulares-con-el-bajo_318-43650.png"));
         System.out.println("Si cargo");
     } catch (Exception e) {
         System.out.println("no cargo por: " + e);
     }
 }
    @Override
    protected void paintComponent(Graphics g){
        g.setColor(getBackground());
        g.fillRect(0, 0, getWidth(), getHeight());
        g.setColor(getForeground());
            int i;
    
        // draw the rows
        int rowHt = height / (rows);
        g.setColor(Color.BLACK);
        for (i = 0; i < rows; i++){
         g.drawLine(0, i * rowHt, width, i * rowHt);
        }
        // draw the columns
        int rowWid = width / (cols);
        g.setColor(Color.BLACK);

        for (i = 0; i < cols; i++){    
          g.drawLine(i * rowWid, 0, i * rowWid, height);
        }
        try{
            ArrayList<Fuente> fuentes = Aswos.getAswos().getSimulacion().getEscenario().getFuentes();
            if (fuentes != null){
                for (Fuente fuente : fuentes) {
                    g.drawImage(image, (int) (fuente.getPosicion())[0], (int) (fuente.getPosicion())[1], null);
                }

            }
        }
        catch(Exception e){
            System.out.println("entro a catch " + e.toString());
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 672, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 376, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
